from tkinter import *
import random

# Score and time left.
# The boolean is used to check if text is correct.
score = 0
time_left = 0
text_correct = False
WPM = 0
day = 0

# Lists for speech
mum_speech = ["Son, why didn't you do your homework?",
              "Son... You are ugly.",
              "Why did you get 'not achieved' for maths.",
              "You are a disgrace.",
              "I told you to wash the dishes!",
              "You spent 10 hours playing games yesterday!",
              "Go to sleep earlier.",
              "Lose some fat son.",
              "Do some more studying.",
              "Play less games!",
              "You broke the TV again...",
              "Clean your room.",
              "You stink, take a shower.",
              "You're going to be late for school!",
              "Stop being so annoying.",
              "Do your homework!",
              "Are your really going to play LoL all day?",
              "You suck at Overwatch.",
              "CSGO? Grow up son.",
              "You never listen, do you?"]

easy_text_choice = ["sorry", "please forgive me", "cupcakes", "whales",
                    "gorillas", "love is in the air", "Jesus is with us",
                    "life is good", "I am so cool", "I do not understand",
                    "cheeseburger", "apples are tasty",
                    "I regret nothing", "my mum is cool",
                    "potato", "hallelujah"]

medium_text_choice = ["I beg for your mercy", "Let's resolve this peacefully",
                      "I don't want to die", "Please don't kill me",
                      "Here, have an apple", "I just followed my destiny",
                      "There is a reason for everything", "There is no need to be angry",
                      "If there is a will there is a way", "Please calm down mum",
                      "Let's set aside our differences", "Let's sing a song",
                      "Video games are the meaning of life",
                      "Let me live another day", "I need to go to the toilet",
                      "We learn from our mistakes"]

hard_text_choice = ["Bring it on mum! I'm ready to fight you.",
                    "Do we really have to do this everyday?",
                    "Why you gotta be so cruel?",
                    "I'm sorry. I'm very sorry.",
                    "I will never touch video games again.",
                    "Someone... Please... Help me...",
                    "The only thing I want for Christmas is your forgiveness.",
                    "You look happy today.",
                    "I don't know why you're mad.",
                    "I've always wondered why the timer is slower than a minute.",
                    "I want to touch up the UI, but I'm a bit lazy...",
                    "I've basically given up on dialogue now.",
                    "Don't make a game about arguing with your mum kids.",
                    "I don't want to do this anymore.",
                    "Make it stop! Make it stop!",
                    "Please, just end the pain already! Just end it!"]

nightmare_text_choice = ["Do you really intend to kill me? Surely you don't want to end up in jail?",
                         "I suggest you take a short rest mother, too much stress will cause your skin to age.",
                         "The entropy of the universe continues to increase through your limitless anger.",
                         "You don't intend to break the 4th law of Thermodynamics, do you?",
                         "I did it mum! I did it! I finally broke the 30 WPM barrier!",
                         "You know what would be interesting? What if this was all a game?",
                         "I will go to the mountains to contemplate my actions.",
                         "The amount of thermal energy generated by you could be the reason for global warming.",
                         "Keep calm and have a cookie. They're surprisingly good.",
                         "There are many twists and turns in the game of life...",
                         "When I was 5 years old, I remember dropping an egg on the floor and getting beat up by mum.",
                         "Forgive me mother! I will do anything you ask! Anything!!!",
                         "Look over there! It's a bamboo shot!",
                         "The truth is... I've always admired you since I was young, mother...",
                         "The organization is after us! We have to run.",
                         "I'm dead. I'm dead. I'm dead. I'm dead. I'm dead. I'm dead. I'm dead."]

# What is going to be in the instructions
instructions_text = """
You are arguing with your mum.
Your goal to is respond quickly to your mum's onslaught with whatever word you can think of.
When your mum shouts something in the speech bubble at the top of the screen,
you may choose to respond with any three of the options at the bottom of the screen.
You can respond by typing the option in the entry field.
The more statements you respond to, the higher your score.
The onslaught will continue for 1 minute, which is when your mum will get tired.
Your words per minute and final score will be presented at the end of the game.
Please remember to click on the entry field before starting.
Make sure you pay careful attention to capital letters,
you must use uppercase when required or else it will be incorrect.
Each time you play the game, the difficulty level will rise.
Good luck!
"""


random_text_choice = [easy_text_choice[random.randint(0, 15)], easy_text_choice[random.randint(0, 15)],
                      easy_text_choice[random.randint(0, 15)]]


# When enter event is triggered, the game starts
def start_game(event):
    global entry_field
    global main_screen
    global score
    global time_left
    if time_left == 6000:
        mum_speech_select()
        countdown()

    # When the game ends, resets everything.
    if time_left == 0:
        global day
        main_screen.delete("all")
        main_screen.create_text(650, 300, fill="black", font=('Helvetica', 150), text="DAY {}".format(day+1))
        main_screen.create_text(650, 400, fill="black", font="Times 20", text="Press enter to start")
        option_screen.configure(text="")
        wpm_label.configure(text="WPM: 0")
        score_display.configure(text="score: 0")
        main_frame.pack_forget()
        start_screen.pack()
        data_reset()


# The timer. Checks the entry field every second to see if requirements are met.
def countdown():
    global time_left
    global timer
    global text_correct
    global score
    global random_text_choice
    if time_left > 0:
        time_left -= 1
        timer.configure(text="Time left: " + str(time_left/100))
        text_correct = False
        option_screen.configure(text="1) " + random_text_choice[0] + "\n\n" +
                                     "2) " + random_text_choice[1] + "\n\n" +
                                     "3) " + random_text_choice[2])
        check_text(entry_field.get())

        if text_correct:
            mum_speech_select()
            score += 1
            score_display.configure(text="score: {}".format(score))
            text_correct = False
        timer.after(10, countdown)

    else:
        end_game()


# Clears the canvas and entry field and then selects a random "mum_speech" from the list.
def mum_speech_select():
    global mum_speech
    global main_screen
    global speech_bubble_image
    global day
    main_screen.delete("all")
    entry_field.delete(0, END)
    text = mum_speech[random.randint(0, 19)]
    if day == 1:
        main_screen.create_image(750, 400, image=bg_room)
    elif day == 2:
        main_screen.create_image(750, 400, image=bg_room2)
    elif day == 3:
        main_screen.create_image(750, 400, image=bg_hill)
    else:
        main_screen.create_image(750, 400, image=bg_hell)
    main_screen.create_image(100, 300, image=mom_image)
    main_screen.create_image(1000, 300, image=son_image)
    main_screen.create_image(1000, 90, image=speech_bubble_image)
    main_screen.create_image(600, 472, image=thought_bubble)
    main_screen.create_text(650, 60, fill="black", font="Times 50", text=text)


# Checks if you have answered the players mother correctly.
def check_text(text):
    global text_correct
    global WPM
    if text == random_text_choice[0] or text == random_text_choice[1] or text == random_text_choice[2]:
        if day == 1:
                random_text_choice[0] = easy_text_choice[random.randint(0, 15)]
                random_text_choice[1] = easy_text_choice[random.randint(0, 15)]
                random_text_choice[2] = easy_text_choice[random.randint(0, 15)]
        elif day == 2:
                random_text_choice[0] = medium_text_choice[random.randint(0, 15)]
                random_text_choice[1] = medium_text_choice[random.randint(0, 15)]
                random_text_choice[2] = medium_text_choice[random.randint(0, 15)]
        elif day == 3:
                random_text_choice[0] = hard_text_choice[random.randint(0, 15)]
                random_text_choice[1] = hard_text_choice[random.randint(0, 15)]
                random_text_choice[2] = hard_text_choice[random.randint(0, 15)]
        else:
                random_text_choice[0] = nightmare_text_choice[random.randint(0, 15)]
                random_text_choice[1] = nightmare_text_choice[random.randint(0, 15)]
                random_text_choice[2] = nightmare_text_choice[random.randint(0, 15)]
        timer.after(0, print_correct)
        timer.after(300, delete_correct)
        WPM += int(len(entry_field.get())/5)
        wpm_label.configure(text="WPM: {}".format(WPM))
        entry_field.delete(0, END)
        text_correct = True


# Prints a massive green 'O' onto the screen.
def print_correct():
    main_screen.create_text(650, 300, fill="green", font="Times 500", text="O", tag="correct")


# Removes the massive 'O'.
def delete_correct():
    main_screen.delete("correct")


# Shows the final score when the game ends.
def end_game():
    global main_screen
    global score
    global time_left
    main_screen.delete("all")
    main_screen.create_text(650, 300, fill="black", font="Times 100 bold", text="The game has ended.")
    main_screen.create_text(650, 400, fill="black", font="Times 20", text="Press enter to continue")
    option_screen.configure(text="Final score: {}      WPM:{}".format(score, WPM))


# Starts the game when 'Play' is pressed.
def start_button_pressed():
    global time_left
    global day
    start_screen.pack_forget()
    main_frame.pack()
    day += 1
    time_left = 6000


# Shows the instructions when 'How to Play' is pressed.
def instructions_button_pressed():
    start_screen.pack_forget()
    instructions_label.pack()
    exit_instructions.pack()


# Returns to menu when this button is pressed.
def return_to_menu():
    instructions_label.pack_forget()
    exit_instructions.pack_forget()
    start_screen.pack()


def data_reset():
    global score
    global time_left
    global text_correct
    global WPM
    score = 0
    time_left = 0
    text_correct = False
    WPM = 0


# Ends the game when 'exit' is pressed.
def exit_button_pressed():
    exit()

# Create window
window = Tk()

# Sets the title and makes window not resizable
window.title("Mom VS Son")
window.resizable(width=False, height=False)

# Main frame
main_frame = Frame(window)

# Top right frame (Top right section)
top_right_frame = Frame(main_frame)

# Score
score_display = Label(top_right_frame, width=15, height=3, text="Score: {}\n".format(str(score)),
                    font=('Helvetica', 22))
score_display.grid(row=0, column=0)

# WPM
wpm_label = Label(top_right_frame, height=3, width=15, text="WPM: {}\n".format(str(score)), font=('Helvetica', 22))
wpm_label.grid(row=1, column=0)

# Timer
timer = Label(top_right_frame, height=3, text="Time left: {}".format(str(time_left / 100)), font=('Helvetica', 22))
timer.grid(row=2, column=0, sticky="W")

# Top left frame (Top left section)
top_left_frame = Frame(main_frame)

# Main screen
main_screen = Canvas(top_left_frame, width=1300, height=600, background="#A7DBDB")
main_screen.create_text(650, 300, fill="black", font=('Helvetica', 150), text="DAY {}".format(day+1))
main_screen.create_text(650, 450, fill="black", font="Times 20", text="Press enter to start")
main_screen.grid(row=0, column=0)

# Creating images
speech_bubble_image = PhotoImage(file="images/speechbubble.gif")
son_image = PhotoImage(file="images/Son.gif")
mom_image = PhotoImage(file="images/Mom.gif")
thought_bubble = PhotoImage(file="images/thought_bubble.gif")
bg_room = PhotoImage(file="images/Empty_room.gif")
bg_room2 = PhotoImage(file="images/room2.gif")
bg_hill = PhotoImage(file="images/grass_hill.gif")
bg_hell = PhotoImage(file="images/hell.gif")

# Option screen
option_screen = Label(top_left_frame, width=75, height=6, text="", font=('Helvetica', 22), bg="white")
option_screen.grid(row=1, column=0)

# Entry frame (Bottom section)
entry_frame = Frame(main_frame, width=1300, height=70)
entry_frame.columnconfigure(0, weight=10)
entry_frame.grid_propagate(False)

# Entry field
entry_string = StringVar()
entry_field = Entry(entry_frame, textvariable=entry_string, font=('Helvetica', 30))
entry_field.grid(sticky="WE")

# Bind event to Return key
window.bind('<Return>', start_game)

# The start screen
start_screen = Canvas(window, width=1600, height=800, bg="#A7DBDB")
start_screen.create_text(800, 200, fill="black", font="Helvetica 120", text="Mom VS Son")
start_screen.pack()

# The instructions label and exit instructions button
instructions_label = Label(window, height=15, text=instructions_text, font="Helvetica 30", bg="#A7DBDB")
exit_instructions = Button(window, width=70, font="Helvetica 30", text="Return to Menu", bg="#69d2e7", command=return_to_menu)

# Grid everything onto main frame
top_right_frame.grid(row=0, column=1, sticky="S")
top_left_frame.grid(row=0, column=0)
entry_frame.grid(row=1, column=0, columnspan=2)

# Buttons attached to the start screen
start_button = Button(start_screen, text="Play", command=start_button_pressed, bg="#69d2e7", font="bold")
instructions_button = Button(start_screen, text="How to Play", command=instructions_button_pressed, bg="#69d2e7", font="bold")
exit_button = Button(start_screen, text="Exit", bg="#69d2e7", font="bold", command=exit_button_pressed)
start_button.place(relx=0.5, rely=0.5, anchor=CENTER, height=50, width=200)
instructions_button.place(relx=0.5, rely=0.6, anchor=CENTER, height=50, width=200)
exit_button.place(relx=0.5, rely=0.7, anchor=CENTER, height=50, width=200)

# Run main loop
window.mainloop()
